---
namespace: ricariel
name: systemd
version: 1.2.9
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: systemd collection
license_file: LICENSE
tags:
  - linux
  - systemd
repository: https://github.com/damex/ansible-collections-systemd
dependencies:
  damex.apt: "*"
