---

name: Pre-Commit Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: https://code.forgejo.org/actions/checkout@v4
    - uses: https://code.forgejo.org/actions/setup-python@v5
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21.0'
    - name: Install detect-secret
      run: pip install detect-secrets
    - uses: https://github.com/pre-commit/action@v3.0.1
      with:
        extra_args: --all-files
